name: CI/CD Pipeline
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Install dependencies
              run: npm install -g pnpm && pnpm install

            - name: TypeScript Check
              run: pnpm tsc

            - name: Lint with Eslint
              run: pnpm lint

            - name: Run Tests
              run: pnpm test --run

            - name: Build project
              run: GQL_GITHUB_TOKEN= pnpm run build
              env:
                  EMAIL_USER: ${{ secrets.EMAIL_USER }}
                  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

            - name: Upload production-ready build files
              uses: actions/upload-artifact@v4
              with:
                name: production-files
                path: ./dist

    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: production-files
                  path: ./dist
            
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
